### ISSUE TITLE
似乎现在不支持多个设备同时使用阿，速度会很慢

### ISSUE THREAD

**Issue by hungry0** [atrandys/wireguard#2]
大佬好，莫非你第二个脚本是解决这个问题的吗？

**Comment by linker001** [comment]
抱歉现在才看到，你要搭建多个用户就可以实现多设备同时使用了。但是我没有搭建多用户同时使用，所以效果怎么样还不清楚。同时据其他大佬说因为走的是upd，所以它会受运行商的qos影响，就是人家设定了先走tcp的话就会让你的速度大大降低。建议：
1.你先试试单用户是否会有很大的影响，若你的单人用户都很慢，那别说多人的了。
2.若单人用户很快，你可以尝试多人用户，别一开就很多，慢慢来试，毕竟运行商是否做了手脚我就不清楚了。
3.tg找我更容易。
________________________________
发件人: zeyu.li <notifications@github.com>
发送时间: 2018年11月13日 8:07
收件人: yobabyshark/wireguard
抄送: Subscribed
主题: [yobabyshark/wireguard] 似乎现在不支持多个设备同时使用阿，速度会很慢 (#2)


大佬好，莫非你第二个脚本是解决这个问题的吗？

―

**Comment by hungry0** [comment]
回复速度很快呀，不慢不慢，哈哈

我就试了两个设备，速度就大大降低，你说的搭建多个用户有什么关键字可以搜索吗，我不是专业的，业余选手，哈哈哈哈

**Comment by atrandys** [comment]
> 回复速度很快呀，不慢不慢，哈哈
> 
> 我就试了两个设备，速度就大大降低，你说的搭建多个用户有什么关键字可以搜索吗，我不是专业的，业余选手，哈哈哈哈

一个peer同一时间只能有一台设备保持连接，多加几个peer，每个设备分配一个就可以了。

**Comment by hungry0** [comment]
好，感谢

**Comment by jovialsidney** [comment]
配置多用户就可以了，一个VMP实例，可以同时设置多个节点
