### ISSUE TITLE
连上了vpn server,但是访问显示IP的网站，为什么显示的还是我的isp分配给我的ip而非vps的IP?

### ISSUE THREAD

**Issue by luckypoem** [atrandys/wireguard#3]
hello.

客户端配置文件内容：
[Interface]
PrivateKey = hidden
Address = 10.0.0.2/24 
DNS = 8.8.8.8
MTU = 1420

[Peer]
PublicKey = hidden
Endpoint = my-vps-ip:21039
AllowedIPs = 0.0.0.0/0, ::0/0
PersistentKeepalive = 25

服务器端配置文件内容：
[Interface]
PrivateKey = hidden
Address = 10.0.0.1/24 
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 21039
DNS = 8.8.8.8
MTU = 1420

[Peer]
PublicKey = hidden
AllowedIPs = 10.0.0.2/32

然后我在mac上运行：
sudo ./tunsafe start ~/wg-client-from-bwg-kvm-vps.conf
Password:
Loading file: /Users/brite/wg-client-from-bwg-kvm-vps.conf
Run: /sbin/ifconfig utun1 10.0.0.2 mtu 1420 10.0.0.2 netmask 255.255.255.0 up
Run: /sbin/route -q add 10.0.0.0/24 10.0.0.2
add net 10.0.0.0: gateway 10.0.0.2
Run: /sbin/route -q add my-vps-ip/32 10.0.0.1
add net my-vps-ip: gateway 10.0.0.1
Run: /sbin/route -q add 0.0.0.0/1 10.0.0.1
add net 0.0.0.0: gateway 10.0.0.1
Run: /sbin/route -q add 128.0.0.0/1 10.0.0.1
add net 128.0.0.0: gateway 10.0.0.1
Sending handshake...
Connection established. IP 10.0.0.2

但是我访问显示IP的网站，显示的还是我的isp分配给我的ip而非vps的IP。
为什么？如何解决？谢谢你.

客户端程序，我用的是https://github.com/TunSafe/TunSafe ，

**Comment by linker001** [comment]
这个是刚安装的嘛？在手机端上是否正常的使用？若是正常使用则把conf文件复制到mac的文件夹进去就可以.若没法证实是否正常运行状态，则要去找ubuntu相关的 我用的contos系，其他的系统没有装过故不要清楚.

发自我的 iPhone

在 2018年11月14日，上午10:15，luckypoem <notifications@github.com<mailto:notifications@github.com>> 写道：


hello.

客户端配置文件内容：
[Interface]
PrivateKey = hidden
Address = 10.0.0.2/24
DNS = 8.8.8.8
MTU = 1420

[Peer]
PublicKey = hidden
Endpoint = my-vps-ip:21039
AllowedIPs = 0.0.0.0/0, ::0/0
PersistentKeepalive = 25

服务器端配置文件内容：
[Interface]
PrivateKey = hidden
Address = 10.0.0.1/24
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 21039
DNS = 8.8.8.8
MTU = 1420

[Peer]
PublicKey = hidden
AllowedIPs = 10.0.0.2/32

然后我在mac上运行：
sudo ./tunsafe start ~/wg-client-from-bwg-kvm-vps.conf
Password:
Loading file: /Users/brite/wg-client-from-bwg-kvm-vps.conf
Run: /sbin/ifconfig utun1 10.0.0.2 mtu 1420 10.0.0.2 netmask 255.255.255.0 up
Run: /sbin/route -q add 10.0.0.0/24 10.0.0.2
add net 10.0.0.0: gateway 10.0.0.2
Run: /sbin/route -q add my-vps-ip/32 10.0.0.1
add net my-vps-ip: gateway 10.0.0.1
Run: /sbin/route -q add 0.0.0.0/1 10.0.0.1
add net 0.0.0.0: gateway 10.0.0.1
Run: /sbin/route -q add 128.0.0.0/1 10.0.0.1
add net 128.0.0.0: gateway 10.0.0.1
Sending handshake...
Connection established. IP 10.0.0.2

但是我访问显示IP的网站，显示的还是我的isp分配给我的ip而非vps的IP。
为什么？如何解决？谢谢你.

客户端程序，我用的是https://github.com/TunSafe/TunSafe ，

**Comment by luckypoem** [comment]
是刚安装的.我没在手机端上试过。没安卓手机，iphone上又没相应的客户端。我的vps 也是centos7，就是用你这个一键脚本安装了wireguard.

**Comment by atrandys** [comment]
> 是刚安装的.我没在手机端上试过。没安卓手机，iphone上又没相应的客户端。我的vps 也是centos7，就是用你这个一键脚本安装了wireguard.

iOS是有测试版软件的：wg官方的或Tunsafe的，我测试Tunsafe在iOS是OK的。

另外IP问题请检查你本地路由表，是否有其他VPN生成的路由。

**Comment by luckypoem** [comment]
@yobabyshark 
如何检查本地路由表是否有其他VPN生成的路由？命令是什么？

**Comment by luckypoem** [comment]
哦，我会做了：
sudo route add vps-public-ip router-ip
sudo route delete default
sudo route add default vps-internal-ip via router-ip

访问显示IP的网站，显示的就是vps的IP了
