### ISSUE TITLE
老哥你好

### ISSUE THREAD

**Issue by 344524488** [atrandys/wireguard#4]
请问怎么让单账号支持多用户啊，现在多人连接其中一个会没网

**Comment by atrandys** [comment]
不能，一个配置文件（peer）对应一个客户端

**Comment by jovialsidney** [comment]
> 请问怎么让单账号支持多用户啊，现在多人连接其中一个会没网

不是单账号支持多用户，是配置多用户，请参考这个视频https://www.youtube.com/watch?v=ZcbDFQiiYvA&index=31&t=85s&list=PLkG4JkWhqK96ze3cXfZzGsD0a9EKH8u-9
