### ISSUE TITLE
我发现一个WG搭配$$一起使用的方法，这样子就可以解决路由的问题

### ISSUE THREAD

**Issue by Dreamone1** [atrandys/wireguard#9]
假设：你服务端上的$$监听端口是23333
你服务端wg的Interface地址是:10.0.0.1/24
你客户端wg的Interface地址是:10.0.0.2/24，修改一下你的conf文件里的AllowedIPs地址为:10.0.0.1/24
那么就可以在$$的客户端的连接地址上写:10.0.0.1，剩下的什么端口都是填写$$的端口和密码

**Comment by Dreamone1** [comment]
这样子就可以解决wg路由表的问题了

**Comment by Dreamone1** [comment]
更好玩的是，按照我的理解$$封装了你的流量----客户端wg封装流量-----服务端wg解包流量-----服务端$$解包你的流量

**Comment by cywy** [comment]
> 假设：你服务端上的$$监听端口是23333 
> 你服务端WG的接口地址是：10.0.0.1/24 
> 你客户端的WG的接口地址是：10.0.0.2/24，修改一下你的CONF文件里的AllowedIPs地址为：10.0.0.1/24 
> 那么就可以在$$的客户端的连接地址上写：10.0.0.1，剩下的什么端口都是填写$$的端口和密码

没太懂，可以看下你的配置吗（敏感信息请注意打码）

**Comment by atrandys** [comment]
https://www.atrandys.com/2019/1752.html
